name: Validação de HTML

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar HTMLHint
        run: npm install -g htmlhint

      - name: Validar HTML
        run: htmlhint index.html
