name: HTML Validation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Validate HTML
        run: htmlhint index.html

